config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :lists do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :tasks

  validates :title, presence: true
end

app/models/long_task.rb
class LongTask < Task
  validates :percentage, presence: true, :inclusion => 0..100

  validates :start_date, :end_date, absence: true

  def valid_states
    super << 'in_progress'
  end
end

app/models/priority.rb
class Priority < ApplicationRecord
  has_many :tasks

  validates :name, presence: true
end

app/models/simple_task.rb
class SimpleTask < Task
  validates :start_date, :end_date, :percentage, absence: true
end

app/models/state.rb
class State < ApplicationRecord
  has_many :tasks

  validates :name, presence: true

  def pending?
    name == 'pending'
  end

  def in_progress?
    name == 'in_progress'
  end

  def finished?
    name == 'finished'
  end

  def expired?
    name == 'expired'
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list, touch: true
  belongs_to :state
  belongs_to :priority

  validates :list, presence: true
  validates :state, presence: true
  validates :priority, presence: true

  validates :description, presence: true

  validate :valid_state

  def partial_name
    type.underscore
  end

  def simple?
    type == 'SimpleTask'
  end

  def long_task?
    type == 'LongTask'
  end

  def temporary_task?
    type == 'TemporaryTask'
  end

  def has_expired?
    false
  end

  def valid_states
    ['pending', 'finished']
  end

  private

  def valid_state
    unless state.nil?
      errors.add(:state, "invalid for this type of task") unless valid_states.include?(state.name)
    end
  end
end

app/models/temporary_task.rb
class TemporaryTask < Task
  validates :start_date, presence: true
  validates :end_date, presence: true

  validates :percentage, absence: true

  validate :start_is_lower_than_end

  def has_expired?
    end_date <= Date.today
  end

  def valid_states
    super << 'expired'
  end

  private

  def start_is_lower_than_end
    unless start_date.nil? || end_date.nil?
      errors.add(:start_date, "should be before end date") if start_date > end_date
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_browser_lists
    session[:current_browser_lists] ||= []
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.find(current_browser_lists).last(5)
    @list = List.new
  end

  def show
    # Mark Temporary tasks as expired
    @list.tasks.each do |task|
      if task.has_expired?
        task.update(state: State.find_by(name: 'expired'))
      end
    end

    @tasks = @list.tasks.order(priority_id: :desc)
    @slug_link = url_for controller: 'lists', action: 'show', only_path: false
  end

  def edit
  end

  def create
    @list = List.new(list_params)

    if @list.save
      current_browser_lists << @list.id
      redirect_to @list, notice: 'List was successfully created.'
    else
      @lists = List.find(current_browser_lists).last(5)
      render :index
    end
  end

  def update
    if @list.update(list_params)
      redirect_to @list, notice: 'List was successfully updated.'
    else
      render :show
    end
  end

  # def destroy
  #   @list.destroy
  #   respond_to do |format|
  #     redirect_to lists_url, notice: 'List was successfully destroyed.'
  #   end
  # end

  private
    def set_list
      @list = List.find_by(slug: params[:id])
    end

    def list_params
      params.require(:list).permit(:title)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def new
    @task = Task.new
    @list = List.find_by(slug: params[:list_id])
    @type = params[:type]
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.list = List.find_by(slug: params[:list_id])
    @task.state = State.find_by(name: 'pending')

    if @task.save
      redirect_to @task.list, notice: 'Task was successfully created.'
    else
      @task = @task.becomes(Task)
      @list = List.find_by(slug: params[:list_id])
      @type = @task.type

      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to @task.list, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

 # def destroy
 #   @task.destroy
 #   respond_to do |format|
 #     redirect_to lists_url, notice: 'List was successfully destroyed.'
 #   end
 # end


  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:type, :state_id, :priority_id, :description, :start_date, :end_date, :percentage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/_errors.html.erb
<div class="alert alert-danger">
  <h2>Correct these errors before submiting</h2>
  <ul>
    <% errors.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_form_errors.html.erb
<div class="alert alert-danger">
  <h2>Correct these errors before submiting</h2>
  <ul>
    <% errors.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manhador de tareas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h1>Manejador de tareas</h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Lists</h2>

<% if @lists.any? %>
  <div class="row">
    <div class="col-sm-6">
      <ul class="list-group">
        <% @lists.each do |list| %>
          <li class="list-group-item">
            <span class="badge"><%= list.tasks.count %></span>
            <%= link_to list.title, list %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% else %>
  <h3>There are no lists to show yet</h3>
<% end %>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :title, required: true %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @list.title %>

  <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#list-modal">
    <i class="glyphicon glyphicon-pencil"></i>
  </button>
</h2>

<% if @list.errors.any? %>
  <script>
    $(window).load(function(){
        $('#list-modal').modal('show');
    });
  </script>
<% end %>
<div class="modal fade in" id="list-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= simple_form_for(@list) do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Edit List Name</h4>
        </div>
        <div class="modal-body">
          <%= f.input :title %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-3">
    <label>This list was created</label>
  </div>

  <div class="col-sm-3">
    <label>Last modified</label>
  </div>

  <div class="col-sm-6">
    <label>Link to this list</label>
  </div>
</div>

<div class="row">
  <div class="col-sm-3">
    <p><%= @list.created_at.to_formatted_s(:long) %></p>
  </div>

  <div class="col-sm-3">
    <p><%= @list.updated_at.to_formatted_s(:long) %></p>
  </div>

  <div class="col-sm-6">
    <code><%= link_to @slug_link %></code>
  </div>
</div>


<h3>Tasks</h3>

<div>
  <% unless @tasks.empty? %>
    <% @tasks.each do |task| %>
      <% unless task.state.expired? %>
        <div>
          <%= render 'tasks/task', task: task %>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <h2>There are no tasks in this list</h2>
  <% end %>
</div>

<div>
  <%= link_to 'New Simple Task', new_list_task_path(@list, type: 'SimpleTask'), class: 'btn btn-default' %>
  <%= link_to 'New Long Task', new_list_task_path(@list, type: 'LongTask'), class: 'btn btn-default' %>
  <%= link_to 'New Temporary Task', new_list_task_path(@list, type: 'TemporaryTask'), class: 'btn btn-default' %>
</div>

<%= link_to 'Back', lists_path, class: 'btn btn-default'  %>

app/views/tasks/_edit_form.html.erb
<%= form.input :description, error: false %>
<%= form.input :priority_id, collection: Priority.all.collect{ |p| [ p.name.humanize, p.id ] }, required: true %>

<% if type == 'LongTask' %>
  <%= form.input :percentage, as: :integer %>
<% elsif type == 'TemporaryTask' %>
  <%= form.input :start_date, required: true %>
  <%= form.input :end_date, required: true %>
<% end %>

<% if show_state_select %>
<%= form.input :state_id,
               collection: State.where(name: task.valid_states).collect{ |s| [ s.name.humanize, s.id ] },
               required: true %>
<% end %>

<% if task.errors.any? %>
  <%= render 'layouts/form_errors', errors: task.errors.full_messages %>
<% end %>

<%= form.button :submit %>

app/views/tasks/_long_task.html.erb
<label>Percentage</label>
<p><%= task.percentage %>%</p>

app/views/tasks/_task.html.erb
<div class="panel panel-<%= task.state.finished? ? 'default' : 'primary' %>">
  <div class="panel-heading">
    <div class="btn-group pull-right">
      <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-<%= task.id %>">
        <i class="glyphicon glyphicon-pencil"></i>
      </button>
    </div>

    <h4>
      <%= task.description %>
    </h4>
  </div>

  <div class="panel-body">
    <div >
      <label>Priority</label>
      <p><%= task.priority.name.humanize %></p>

      <label>State</label>
      <p><%= task.state.name.humanize %></p>

      <label>Type</label>
      <p><%= task.type.titleize %></p>

      <%= render "tasks/#{task.partial_name}", task: task %>
    </div>

  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal-<%= task.id %>" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= simple_form_for([task.list, task.becomes(Task)], url: list_task_path(task.list, task)) do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Edit <%= task.type.titleize %></h4>
        </div>
        <div class="modal-body">
            <%= render 'tasks/edit_form', form: f, task: task, type: task.type, show_state_select: true %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_temporary_task.html.erb
<label>Start Date</label>
<p><%= task.start_date %></p>

<label>End Date</label>
<p><%= task.end_date %></p>

app/views/tasks/edit.html.erb
<h2>Edit <%= @task.type.titleize %></h2>

<%= simple_form_for([@task.list, @task.becomes(Task)], url: list_task_path(@task.list, @task)) do |f| %>
  <%= render 'edit_form', form: f, task: @task, type: @task.type show_state_select: true %>
<% end %>

<%= link_to 'Back', lists_path, class: 'btn btn-default' %>

app/views/tasks/new.html.erb
<h2>New <%= @type.titleize %></h2>

<%= simple_form_for([@list, @task], url: list_tasks_path) do |f| %>
  <%= f.hidden_field :type, value: @type %>
  <%= render 'edit_form', form: f, task: @task, type: @type, show_state_select: false %>
<% end %>

<%= link_to 'Back', lists_path %>